jobs:
  include:
    - stage: preflight
      env: TASK=travis-format

    - stage: libraries
      env: SBT_PROJECT=common
    - env: SBT_PROJECT=display
    - env: SBT_PROJECT=ingests_common
    - env: SBT_PROJECT=bags_common

    - stage: services
      env: SBT_PROJECT=archivist
    - env: SBT_PROJECT=ingests
    - env: SBT_PROJECT=ingests_api
    - env: SBT_PROJECT=bags
    - env: SBT_PROJECT=bags_api
    - env: SBT_PROJECT=notifier
    - env: TASK=bagger-publish

script:
  # Wait 45 minutes for the entire build to finish.  Primarily this stops the
  # build timing out if we're taking a really long time to compile something.
  # See https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
  - travis_wait 45 ./.travis/run_job.py

cache:
  directories:
    - $HOME/docker
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - project/target
    - target

    - archivist/target
    - bags/target
    - bags_api/target
    - bags_common/target
    - bag_replicator/target
    - common/target
    - display/target
    - ingests/target
    - ingests_api/target
    - ingests_common/target
    - notifier/target

stages:
  - preflight
  - libraries
  - services

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in secrets.zip.enc -out secrets.zip -d
  - unzip secrets.zip
  - chmod 600 id_rsa
  - mkdir -p ~/.aws
  - cp config ~/.aws/config
  - cp credentials ~/.aws/credentials

language: sh

services:
  - docker

dist: trusty

branches:
  only:
    - master

# Based on instructions from
# https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html#Caching
before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
  - sudo find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - sudo find $HOME/.sbt        -name "*.lock"               -print -delete

env:
  global:
    # This forces Python to print everything to stdout/stderr immediately.
    # Otherwise, we've seen issues where all the output from our Travis scripts
    # gets buffered, and only gets printed at the end of the test...
    #
    # ... out of order from the rest of the rest of the output!
    #
    # See also: https://docs.python.org/3/using/cmdline.html#cmdoption-u
    #
    - PYTHONUNBUFFERED=x
