sqs:
  image: s12v/elasticmq
  ports:
    - "9324:9324"
    - "4789:9324"
wiremock:
  image: rodolpheche/wiremock
  ports:
    - "8080:8080"
  volumes:
    - "${ROOT}/archive/notifier/src/test/resources/wiremock:/home/wiremock"
